
-- #seed the customers table
INSERT INTO customers (name, address_line_1,address_line_2,postcode,funds,email) VALUES ('Daniel Smith','93 Altyre Avenue', 'Glenrothes','KY7 4PY', 100,'dannysmith@blueyonder.co.uk');
INSERT INTO customers (name, address_line_1,address_line_2,postcode,funds,email) VALUES ('Stephen Ritchie','113 Martin Crescent', 'Ballingry','KY5 8PU', 100,'bigstevie@blueyonder.co.uk');
INSERT INTO customers (name, address_line_1,address_line_2,postcode,funds,email) VALUES ('Maureen Guppy','6 Strathye Place', 'Glenrothes','KY7 6XQ', 100, 'andrew.guppy@blueyonder.co.uk');

-- seed the products table
INSERT INTO products (specie,latin_name, image, price, quantity, comments) VALUES ('Full Red Guppy', 'poecilia reticulata','./images/red_guppies.JPG',1.50,10, 'Males are about half the size of females with colorful tail and caudal fin, the anal fin is transformed into a gonopodium for internal fertilization. Males are continuously chasing and mating females. Females can store sperms for later fertilization and may produce young every four weeks. Pregnant females are recognizable by black triangle between anal and pelvic fins. After a gestation period of four to six weeks females give birth to 20-40 live young. No parental care is exercised and parents may even prey on their young.');
INSERT INTO products (specie,latin_name, image, price, quantity,comments) VALUES ('Red Robin Gourami', 'Colisa chuna','./images/red_robin Gourami.jpg',2.50,5,'A peaceful species that benefits from a fairly large aquaria. The tank should be densely planted and also contain some floating plants if possible Its tank-mates should be small peaceful lower tank dwelling species. Feeding is not a problem as they take prepared staple food along with supplements of live and frozen food. Temperature range of mid seventies to low eighties. They dwell in the middle to upper areas of the tank.
');
INSERT INTO products (specie,latin_name, image, price, quantity, comments) VALUES ('Apisto Borelli - Yellow head', 'Apistogramma Borelli','./images/Apistogramma_Borelli_Yellow_headed_male.JPG',6.95,4,'In the wild, Apistogramma borellii inhabit slow-moving shallow creeks and tributaries of the Rio Paraguay and the lower Rio Paraná basins, and in many places the substrate is composed of leaf litter. This dwarf cichlid is most noted for its striking colour formations, particularly in the male fish; the front end of the body is predominantly golden yellow, the flanks and posterior of the body with striking metallic powder blue undertones, and the fins gold-tipped. The home aquarium should contain soft, acidic water of cooler than average temperature (see above), and be well matured before these fishes are added. Ideally there will be dark substrate and dense planting, with plenty of hiding places/territories amongst rocks and bogwood. These fish are not fussy about the appearance of the décor, and clean, new terracotta flower pots and the like will be much appreciated.');
INSERT INTO products (specie,latin_name, image, price, quantity, comments) VALUES ('Albino Kribensis PAIR', 'pelvicachromis kribensis','./images/Albino_Krib.jpg',11.25,2, E'Introduced to the hobby in the 1950s. One look at this beautiful fish and you can see why it immediately became favored. It is still a popular fish today and makes a great choice for a new hobbyist interested in keeping cichlids\nBeauty is one of their most attractive features and they have interesting behaviors. They are entertaining to watch and being small in size makes them more manageable than many of the other cichlid species. They are easy to keep, easy to feed, and are fairly easy to breed. They can be kept in a smaller aquarium and are relatively undemanding in their water chemistry as long as it is consistent.');

-- seed the sales table
INSERT INTO receipts (customer_id,product_id, purchase_type, purchase_time, delivery_type) VALUES (1, 2,'online',timeofday(),'delivery');
INSERT INTO receipts (customer_id,product_id, purchase_type, purchase_time, delivery_type) VALUES (2, 1,'in-store',timeofday(),'collection');
INSERT INTO receipts (customer_id,product_id, purchase_type, purchase_time, delivery_type) VALUES (1, 1,'auction',timeofday(),'delivery');

-- put a couple in the basket
INSERT INTO basket (customer_id, specie, price, quantity) VALUES (1, 'Red Robin Gourami', 3.25, 2);
INSERT INTO basket (customer_id, specie, price, quantity) VALUES (1, 'Full Red Guppy',1.25, 5);